import {
  ROOM_ICON_GROUPS,
  type RoomIconName,
} from "@calcom/features/ne26-rooms/lib/roomIcons";
import {
  Airplay,
  Antenna,
  Armchair,
  Award,
  BadgeCheck,
  Beer,
  Blinds,
  Bluetooth,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Building2,
  Cable,
  Cake,
  CalendarClock,
  Cast,
  ChartColumn,
  ChartNoAxesColumn,
  CircleUserRound,
  ClipboardList,
  Clock,
  Coffee,
  Columns3,
  Contact,
  Croissant,
  Crown,
  CupSoda,
  Diamond,
  DoorClosed,
  DoorOpen,
  Eye,
  FileText,
  Fingerprint,
  Flag,
  Flame,
  Frame,
  Gem,
  GlassWater,
  Globe,
  Handshake,
  Headphones,
  Hotel,
  IdCard,
  KeyRound,
  LampCeiling,
  LampDesk,
  Landmark,
  Laptop,
  LaptopMinimal,
  LayoutGrid,
  Lightbulb,
  Lock,
  Map,
  MapPin,
  Martini,
  Maximize,
  Medal,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  MicVocal,
  Monitor,
  MonitorPlay,
  Mountain,
  Network,
  Notebook,
  NotebookPen,
  PanelsTopLeft,
  PenTool,
  Pencil,
  PhoneCall,
  Plug,
  Podcast,
  Power,
  Presentation,
  Projector,
  Radio,
  Rocket,
  Rows3,
  Sandwich,
  ScanFace,
  ScreenShare,
  Settings,
  Shield,
  ShieldCheck,
  Signal,
  Sofa,
  Soup,
  Sparkles,
  Speaker,
  Speech,
  Star,
  Target,
  TreePalm,
  TrendingUp,
  Trophy,
  Tv,
  Usb,
  User,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  Video,
  Volume2,
  Warehouse,
  Wifi,
  Wine,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * The stand-in for a room with no photograph yet.
 *
 * One building glyph for all nine rooms made the listing unreadable while the
 * photos were missing: a Suite and a Small Room looked identical in the place
 * where the buyer is deciding between them.
 *
 * Which glyph is now the administrator's choice, not a rule derived from the
 * price band — the person who knows what a room is used for is the one selling
 * it. The category default is only what a room starts with.
 */
const BY_NAME: Record<RoomIconName, LucideIcon> = {
  Presentation,
  Projector,
  ScreenShare,
  Monitor,
  Tv,
  MonitorPlay,
  Airplay,
  Cast,
  Armchair,
  Sofa,
  DoorOpen,
  DoorClosed,
  Blinds,
  LampDesk,
  LampCeiling,
  Frame,
  PanelsTopLeft,
  Columns3,
  Rows3,
  LayoutGrid,
  Maximize,
  Users,
  UsersRound,
  User,
  UserRound,
  Handshake,
  MessagesSquare,
  MessageSquare,
  MessageCircle,
  Speech,
  Mic,
  MicVocal,
  Podcast,
  Video,
  PhoneCall,
  Contact,
  IdCard,
  UserPlus,
  CircleUserRound,
  Briefcase,
  BriefcaseBusiness,
  Laptop,
  LaptopMinimal,
  Notebook,
  NotebookPen,
  ClipboardList,
  FileText,
  PenTool,
  Pencil,
  CalendarClock,
  Clock,
  Target,
  Lightbulb,
  Rocket,
  TrendingUp,
  ChartNoAxesColumn,
  ChartColumn,
  Network,
  Workflow,
  Coffee,
  CupSoda,
  Utensils,
  UtensilsCrossed,
  Wine,
  Cake,
  Croissant,
  Sandwich,
  GlassWater,
  Martini,
  Beer,
  Soup,
  Crown,
  Gem,
  Star,
  Sparkles,
  Award,
  Medal,
  Trophy,
  BadgeCheck,
  Diamond,
  Flame,
  Building,
  Building2,
  Landmark,
  Warehouse,
  Hotel,
  MapPin,
  Map,
  Globe,
  Flag,
  TreePalm,
  Mountain,
  Wifi,
  Signal,
  Speaker,
  Volume2,
  Headphones,
  Radio,
  Antenna,
  Plug,
  Power,
  Cable,
  Usb,
  Bluetooth,
  Settings,
  Zap,
  Shield,
  ShieldCheck,
  Lock,
  KeyRound,
  Eye,
  Fingerprint,
  ScanFace,
};

const BY_CATEGORY: Record<string, LucideIcon> = {
  // A suite: the one with a crown on it, because it is the top of the range.
  PREMIUM: Crown,
  // A large room: a screen on a stand, the thing it is used for.
  INTERMEDIATE: Presentation,
  // A small room: a seat, for a conversation between a few people.
  ENTRY: Armchair,
};

/** Every glyph an admin may pick, grouped the way the picker shows them. */
export const ROOM_ICON_CHOICE_GROUPS: {
  label: string;
  icons: { name: RoomIconName; Icon: LucideIcon }[];
}[] = ROOM_ICON_GROUPS.map((g) => ({
  label: g.label,
  icons: g.names.map((name) => ({ name, Icon: BY_NAME[name] })),
}));

/**
 * The room's own glyph if it has been given one, otherwise its category's.
 *
 * Falls back rather than failing: a name that is no longer in the catalogue —
 * an icon retired after a room was saved with it — must still render something
 * on a public page.
 */
export function roomIconFor(category: string, iconName?: string | null): LucideIcon {
  if (iconName && iconName in BY_NAME) return BY_NAME[iconName as RoomIconName];
  return BY_CATEGORY[category] ?? Building;
}
